server:
  port: ${API_PORT:8780}
  servlet:
    context-path: "/api"
  # For include message error to http response!!!
  error:
    include-message: always

spring:
  application:
    name: easybotshop
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  dataSource:
    url: jdbc:h2:mem:easybotdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  hibernate:
    ddl-auto: create-drop
    dialect: org.hibernate.dialect.MySQL57Dialect
    #        generate_statistics: true
  jpa:
    # show SQL statements in console.
    show-sql: true
    #    database-platform: hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  flyway:
    enabled: true
    generate_statistics: true

logging:
  level:
    root: info
  file:
    path: log/

management:
  health:
    probes:
      enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true
    caches:
      enabled: true
    info:
      enabled: true
      show-details: always
    beans:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/api/actuator"
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 8788

