server:
  port: ${API_PORT:8780}
  servlet:
    context-path: "/api"
  # For include message error to http response!!!
  error:
    include-message: always

spring:
  application:
    name: easybotshop
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        spring.hibernate.hbm2ddl.auto: create-drop
  dataSource:
    url: jdbc:h2:mem:rentdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  hibernate:
    ddl-auto: create-drop
    dialect: org.hibernate.dialect.H2Dialect
    #        generate_statistics: true
  main:
    lazy-initialization: true
  flyway:
    enabled: true
    generate_statistics: true
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.use_sql_comments: true
